/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("pbc_4090739454");

  return app.delete(collection);
}, (app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != \"\"",
    "deleteRule": "@request.auth.id != \"\"",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1719394029",
        "max": 50,
        "min": 0,
        "name": "log_code",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_4155943932",
        "hidden": false,
        "id": "relation3968183439",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "farmer",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text214706097",
        "max": 20,
        "min": 0,
        "name": "village_code",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text574155368",
        "max": 200,
        "min": 0,
        "name": "farmer_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text953585943",
        "max": 200,
        "min": 0,
        "name": "variety",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2250053782",
        "max": 100,
        "min": 0,
        "name": "process",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number4280395381",
        "max": null,
        "min": 0,
        "name": "eu_organic_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number477624743",
        "max": null,
        "min": 0,
        "name": "fairtrade_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number216946894",
        "max": null,
        "min": 0,
        "name": "non_certificate_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "date3153123599",
        "max": "",
        "min": "",
        "name": "log_date",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "number1092145443",
        "max": null,
        "min": null,
        "name": "latitude",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number2246143851",
        "max": null,
        "min": null,
        "name": "longitude",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1353946433",
        "max": 200,
        "min": 0,
        "name": "dry_mill_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number3045971753",
        "max": null,
        "min": null,
        "name": "moisture_pct",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number4055634117",
        "max": null,
        "min": null,
        "name": "aw_level",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3362005187",
        "max": null,
        "min": 0,
        "name": "number_of_bags",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number231238641",
        "max": null,
        "min": 0,
        "name": "weight_total_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "date2063794144",
        "max": "",
        "min": "",
        "name": "delivery_date",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3788167225",
        "max": 0,
        "min": 0,
        "name": "remark",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2781714960",
        "max": 50,
        "min": 0,
        "name": "staff_input",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select1400097126",
        "maxSelect": 0,
        "name": "country",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "indonesia",
          "vietnam",
          "laos"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4041497513",
        "max": 20,
        "min": 0,
        "name": "season",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_4090739454",
    "indexes": [
      "CREATE UNIQUE INDEX idx_flb_log_code ON farmer_log_books (log_code)",
      "CREATE INDEX idx_flb_farmer ON farmer_log_books (farmer)",
      "CREATE INDEX idx_flb_country ON farmer_log_books (country)"
    ],
    "listRule": "@request.auth.id != \"\"",
    "name": "farmer_log_books",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.id != \"\"",
    "viewRule": "@request.auth.id != \"\""
  });

  return app.save(collection);
})
