/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("pbc_657985343");

  return app.delete(collection);
}, (app) => {
  const collection = new Collection({
    "createRule": "@request.auth.id != \"\"",
    "deleteRule": "@request.auth.id != \"\"",
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3812208344",
        "max": 50,
        "min": 0,
        "name": "lot_code",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_4155943932",
        "hidden": false,
        "id": "relation3968183439",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "farmer",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_3601257007",
        "hidden": false,
        "id": "relation1477890117",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "farm",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_4090739454",
        "hidden": false,
        "id": "relation200092629",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "farmer_log_book",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_3328706532",
        "hidden": false,
        "id": "relation2189433630",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "farm_log_book",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "relation"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text214706097",
        "max": 20,
        "min": 0,
        "name": "village_code",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3750258723",
        "max": 200,
        "min": 0,
        "name": "farm_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text563927626",
        "max": 300,
        "min": 0,
        "name": "certificate",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text953585943",
        "max": 200,
        "min": 0,
        "name": "variety",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2250053782",
        "max": 100,
        "min": 0,
        "name": "process",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "date3153123599",
        "max": "",
        "min": "",
        "name": "log_date",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1353946433",
        "max": 200,
        "min": 0,
        "name": "dry_mill_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number3045971753",
        "max": null,
        "min": null,
        "name": "moisture_pct",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number4055634117",
        "max": null,
        "min": null,
        "name": "aw_level",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number3362005187",
        "max": null,
        "min": 0,
        "name": "number_of_bags",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number231238641",
        "max": null,
        "min": 0,
        "name": "weight_total_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "number629317863",
        "max": null,
        "min": 0,
        "name": "weight_per_bag_kg",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "hidden": false,
        "id": "date2063794144",
        "max": "",
        "min": "",
        "name": "delivery_date",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text258042846",
        "max": 50,
        "min": 0,
        "name": "sale_status",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3788167225",
        "max": 0,
        "min": 0,
        "name": "remark",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2781714960",
        "max": 50,
        "min": 0,
        "name": "staff_input",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select1400097126",
        "maxSelect": 0,
        "name": "country",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "indonesia",
          "vietnam",
          "laos"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text4041497513",
        "max": 20,
        "min": 0,
        "name": "season",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_657985343",
    "indexes": [
      "CREATE UNIQUE INDEX idx_lbd_lot_code ON log_book_details (lot_code)",
      "CREATE INDEX idx_lbd_farm ON log_book_details (farm)",
      "CREATE INDEX idx_lbd_farm_log ON log_book_details (farm_log_book)"
    ],
    "listRule": "@request.auth.id != \"\"",
    "name": "log_book_details",
    "system": false,
    "type": "base",
    "updateRule": "@request.auth.id != \"\"",
    "viewRule": "@request.auth.id != \"\""
  });

  return app.save(collection);
})
